### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/javafx/embed/HostInterface

### ISSUE THREAD

**Issue by DeadMor0z** [mguessan/davmail#11]
After updating to 5.0.0, I can't get davmail tray icon. If starting from console I get:
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: 
com/sun/javafx/embed/HostInterface
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at davmail.ui.SettingsFrame.isJavaFXAvailable(SettingsFrame.java:267)
        at davmail.ui.SettingsFrame.getSettingsPanel(SettingsFrame.java:164)
        at davmail.ui.SettingsFrame.<init>(SettingsFrame.java:746)
        at davmail.ui.tray.AwtGatewayTray.createAndShowGUI(AwtGatewayTray.java:233)
        at davmail.ui.tray.AwtGatewayTray$7.run(AwtGatewayTray.java:185)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.embed.HostInterface
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 20 more
```
installed:
openjfx, libopenjfx-java (11)
openjdk-11
all other dependencies.
Debian (SID) x64

**Comment by mguessan** [comment]
Could be related to:
https://salsa.debian.org/debian/davmail/commit/6ec7a7a6061727793c0c4dcb9627f933bc4f0440

... if you installed directly from debian repo

**Comment by DeadMor0z** [comment]
added /usr/share/java/javafx-graphics.jar and /usr/share/java/javafx-base.jar to MANIFEST.MF and it helped.
Now davmail starts with this error: `InteropFactory: cannot load com.sun.javafx.embed.swing.newimpl.InteropFactoryN`, but at least tray icon appears and it works (with JavambeddedFrame tooltip, though).

**Comment by mguessan** [comment]
It's probably better to disable tray:
`davmail -notray`

**Comment by mguessan** [comment]
Fixed by debian package maintainers
